<?php

namespace Database\Factories;

use App\Models\Inventory;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Carbon;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Inventory>
 */
class InventoryFactory extends Factory
{
    protected $model = Inventory::class;
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition()
    {
        $medicineName = fake()->randomElement([
            "Aciclovir (Zovirax)",
            "Acrivastine",
            "Adalimumab",
            "Alendronic acid",
            "Allopurinol",
            "Alogliptin",
            "Amitriptyline for depression",
            "Amitriptyline for pain and migraine",
            "Amlodipine",
            "Amoxicillin",
            "Anastrozole",
            "Apixaban",
            "Aripiprazole",
            "Aspirin for pain relief",
            "Aspirin",
            "Atenolol",
            "Atorvastatin",
            "Azathioprine",
            "Azithromycin",
            "Baclofen",
            "Beclometasone inhalers",
            "Beclometasone nasal spray",
            "Beclometasone skin creams",
            "Beclometasone tablets",
            "Bendroflumethiazide",
            "Benzoyl peroxide",
            "Benzydamine",
            "Betahistine",
            "Betamethasone for eyes, ears and nose",
            "Betamethasone for skin",
            "Betamethasone tablets",
            "Bimatoprost",
            "Bisacodyl",
            "Bisoprolol",
            "Brinzolamide",
            "Budesonide inhalers",
            "Budesonide nasal spray",
            "Budesonide rectal foam and enemas",
            "Budesonide tablets, capsules and granules",
            "Bumetanide",
            "Buprenorphine for pain",
            "Buscopan (hyoscine butylbromide)",
            "Calcipotriol",
            "Candesartan",
            "Carbamazepine",
            "Carbimazole",
            "Carbocisteine",
            "Carmellose sodium",
            "Carvedilol",
            "Cefalexin",
            "Cetirizine",
            "Champix (varenicline)",
            "Chloramphenicol",
            "Chlorhexidine",
            "Chlorphenamine (Piriton)",
            "Cinnarizine",
            "Ciprofloxacin",
            "Citalopram",
            "Clarithromycin",
            "Clobetasol",
            "Clobetasone",
            "Clonazepam",
            "Clonidine",
            "Clopidogrel",
            "Clotrimazole cream, spray and solution",
            "Clotrimazole for thrush (Canesten)",
            "Co-amoxiclav",
            "Co-beneldopa",
            "Co-careldopa",
            "Co-codamol for adults",
            "Co-codamol for children",
            "Co-codaprin (aspirin and codeine)",
            "Co-dydramol",
            "Coal tar",
            "Codeine",
            "Colchicine",
            "Colecalciferol",
            "Contraceptive injections (medroxyprogesterone)",
            "Cyanocobalamin",
            "Cyclizine",
            "Dabigatran",
            "Dapagliflozin",
            "Dexamethasone eye drops",
            "Dexamethasone tablets and liquid",
            "Diazepam",
            "Diclofenac",
            "Digoxin",
            "Dihydrocodeine",
            "Diltiazem",
            "Diphenhydramine",
            "Dipyridamole",
            "Docusate",
            "Domperidone",
            "Donepezil",
            "Dosulepin",
            "Doxazosin",
            "Doxycycline",
            "Duloxetine",
            "Edoxaban",
            "Empagliflozin",
            "Enalapril",
            "Eplerenone",
            "Erythromycin",
            "Escitalopram",
            "Esomeprazole",
            "Ezetimibe",
            "Felodipine",
            "Fentanyl",
            "Ferrous fumarate",
            "Ferrous sulfate",
            "Fexofenadine",
            "Finasteride",
            "Flucloxacillin",
            "Fluconazole",
            "Fluoxetine (Prozac)",
            "Fluticasone inhalers",
            "Fluticasone nasal spray and drops",
            "Fluticasone skin creams",
            "Folic acid",
            "Furosemide",
            "Fusidic acid",
            "Fybogel (ispaghula husk)",
            "Gabapentin",
            "Gaviscon (alginic acid)",
            "Gliclazide",
            "Glimepiride",
            "Glyceryl trinitrate (GTN)",
            "Haloperidol",
            "Heparinoid",
            "Hydrocortisone",
            "Hydrocortisone buccal tablets",
            "Hydrocortisone for piles and itchy bottom",
            "Hydrocortisone for skin",
            "Hydrocortisone injections",
            "Hydrocortisone rectal foam",
            "Hydrocortisone tablets",
            "Hydroxocobalamin",
            "Hydroxychloroquine",
            "Hyoscine hydrobromide (Kwells and Joy-Rides)",
            "Ibuprofen and codeine",
            "Ibuprofen for adults (Nurofen)",
            "Ibuprofen for children",
            "Indapamide",
            "Irbesartan",
            "Isosorbide mononitrate and isosorbide dinitrate",
            "Isotretinoin capsules (Roaccutane)",
            "Isotretinoin gel (Isotrex)",
            "Ketoconazole",
            "Labetalol",
            "Lactulose",
            "Lamotrigine",
            "Lansoprazole",
            "Latanoprost",
            "Lercanidipine",
            "Letrozole",
            "Levetiracetam",
            "Levothyroxine",
            "Lidocaine for mouth and throat",
            "Lidocaine for piles and itchy bottom",
            "Lidocaine skin cream",
            "Linagliptin",
            "Lisinopril",
            "Lithium",
            "Loperamide",
            "Loratadine (Clarityn)",
            "Lorazepam",
            "Losartan",
            "Low-dose aspirin",
            "Lymecycline",
            "Macrogol",
            "Mebendazole",
            "Mebeverine",
            "Medroxyprogesterone tablets",
            "Melatonin",
            "Memantine",
            "Mesalazine",
            "Metformin",
            "Methadone",
            "Methotrexate",
            "Methylphenidate for adults",
            "Methylphenidate for children",
            "Metoclopramide",
            "Metoprolol",
            "Metronidazole",
            "Mirabegron",
            "Mirtazapine",
            "Molnupiravir (Lagevrio)",
            "Mometasone for skin",
            "Mometasone inhalers",
            "Mometasone nasal spray",
            "Montelukast",
            "Morphine",
            "Naproxen",
            "Nefopam",
            "Nicorandil",
            "Nifedipine",
            "Nitrofurantoin",
            "Nortriptyline",
            "Nystatin",
            "Olanzapine",
            "Olmesartan",
            "Omeprazole",
            "Oxybutynin",
            "Oxycodone",
            "Pantoprazole",
            "Paracetamol for adults",
            "Paracetamol for children (Calpol)",
            "Paroxetine",
            "Paxlovid",
            "Peppermint oil",
            "Pepto-Bismol (bismuth subsalicylate)",
            "Perindopril",
            "Phenoxymethylpenicillin",
            "Phenytoin",
            "Pioglitazone",
            "Pravastatin",
            "Pre-Exposure Prophylaxis (PrEP)",
            "Prednisolone tablets and liquid",
            "Pregabalin",
            "Prochlorperazine",
            "Promethazine (Phenergan)",
            "Propranolol",
            "Quetiapine",
            "Rabeprazole",
            "Ramipril",
            "Ranitidine",
            "Remdesivir (Veklury)",
            "Risedronate",
            "Risperidone",
            "Rivaroxaban",
            "Ropinirole",
            "Rosuvastatin",
            "Salbutamol inhaler",
            "Saxagliptin",
            "Senna",
            "Sertraline",
            "Sildenafil (Viagra)",
            "Simeticone",
            "Simvastatin",
            "Sitagliptin",
            "Sodium cromoglicate capsules",
            "Sodium cromoglicate eye drops",
            "Sodium valproate",
            "Solifenacin",
            "Sotalol",
            "Sotrovimab (Xevudy)",
            "Spironolactone",
            "Sulfasalazine",
            "Sumatriptan",
            "Tadalafil",
            "Tamsulosin",
            "Temazepam",
            "Terbinafine",
            "Thiamine (vitamin B1)",
            "Ticagrelor",
            "Timolol eye drops",
            "Timolol tablets",
            "Tolterodine",
            "Topiramate",
            "Tramadol",
            "Tranexamic acid",
            "Trastuzumab (Herceptin)",
            "Trazodone",
            "Trimethoprim",
            "Valproic acid",
            "Valsartan",
            "Varenicline",
            "Venlafaxine",
            "Verapamil",
            "Warfarin",
            "Zolpidem",
            "Zopiclone",
        ]);

        $medicineType = fake()->randomElement([
            "Anti-Inflammatory",
            "Antibiotics",
            "Cardiac Drugs",
            "Ear Meds",
            "Topicals",
        ]);

        $balance = random_int(1, 20000);

        return [
            'medicine_name' => $medicineName,
            'brand' => 'generic',
            'manufacturer_date' => fake()->dateTimeBetween('1990-01-01', '2023-05-30'),
            'expiration_date' => fake()->dateTimeBetween('2024-01-01', '2025-05-30'),
            'type' => $medicineType,
            'beginning_balance' => $balance,
            'stock_balance' => $balance,
            'reorder_level' => 50,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now()
        ];
    }
}
